/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarketapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AdminProfile extends javax.swing.JFrame {

    /**
     * Creates new form AdminProfile
     */
    public AdminProfile() {
        initComponents();
        AdminDetails();
    }
    
    //database connect
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close_btn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        logout_btn6 = new javax.swing.JLabel();
        adminID_lbl = new javax.swing.JLabel();
        logout_btn1 = new javax.swing.JLabel();
        adminName_lbl = new javax.swing.JLabel();
        logout_btn7 = new javax.swing.JLabel();
        adminUN_lbl = new javax.swing.JLabel();
        adminPass_lbl = new javax.swing.JLabel();
        logout_btn2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        update_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        back_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        close_btn.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\close-box.png")); // NOI18N
        close_btn.setText("X");
        close_btn.setToolTipText("");
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(87, 145, 179));

        logout_btn6.setBackground(new java.awt.Color(255, 0, 0));
        logout_btn6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logout_btn6.setForeground(new java.awt.Color(51, 51, 51));
        logout_btn6.setText("ADMIN ID :");
        logout_btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btn6MouseClicked(evt);
            }
        });

        adminID_lbl.setBackground(new java.awt.Color(255, 0, 0));
        adminID_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adminID_lbl.setForeground(new java.awt.Color(255, 255, 255));
        adminID_lbl.setText("ID");
        adminID_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminID_lblMouseClicked(evt);
            }
        });

        logout_btn1.setBackground(new java.awt.Color(255, 0, 0));
        logout_btn1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logout_btn1.setForeground(new java.awt.Color(51, 51, 51));
        logout_btn1.setText("NAME :");
        logout_btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btn1MouseClicked(evt);
            }
        });

        adminName_lbl.setBackground(new java.awt.Color(255, 0, 0));
        adminName_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adminName_lbl.setForeground(new java.awt.Color(255, 255, 255));
        adminName_lbl.setText("ADMIN NAME");
        adminName_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminName_lblMouseClicked(evt);
            }
        });

        logout_btn7.setBackground(new java.awt.Color(255, 0, 0));
        logout_btn7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logout_btn7.setForeground(new java.awt.Color(51, 51, 51));
        logout_btn7.setText("USERNAME :");
        logout_btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btn7MouseClicked(evt);
            }
        });

        adminUN_lbl.setBackground(new java.awt.Color(255, 0, 0));
        adminUN_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adminUN_lbl.setForeground(new java.awt.Color(255, 255, 255));
        adminUN_lbl.setText("ADMIN USERNAME");
        adminUN_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminUN_lblMouseClicked(evt);
            }
        });

        adminPass_lbl.setBackground(new java.awt.Color(255, 0, 0));
        adminPass_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        adminPass_lbl.setForeground(new java.awt.Color(255, 255, 255));
        adminPass_lbl.setText("ADMIN PASSWORD");
        adminPass_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPass_lblMouseClicked(evt);
            }
        });

        logout_btn2.setBackground(new java.awt.Color(255, 0, 0));
        logout_btn2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        logout_btn2.setForeground(new java.awt.Color(51, 51, 51));
        logout_btn2.setText("PASSWORD :");
        logout_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btn2MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\profile_large.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel1)
                .addGap(154, 154, 154)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logout_btn7)
                            .addComponent(logout_btn1)
                            .addComponent(logout_btn6))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminName_lbl)
                            .addComponent(adminUN_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminID_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(logout_btn2)
                        .addGap(18, 18, 18)
                        .addComponent(adminPass_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout_btn6)
                            .addComponent(adminID_lbl))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout_btn1)
                            .addComponent(adminName_lbl))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout_btn7)
                            .addComponent(adminUN_lbl))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logout_btn2)
                            .addComponent(adminPass_lbl))))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        update_btn.setBackground(new java.awt.Color(87, 145, 179));
        update_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        update_btn.setForeground(new java.awt.Color(51, 51, 51));
        update_btn.setText("UPDATE ADMIN");
        update_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_btnMouseClicked(evt);
            }
        });
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\grocerypals_small.png")); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\cart_small.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(update_btn)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close_btn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel7)))
                .addGap(149, 149, 149)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(87, 145, 179));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROFILE");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        back_btn.setBackground(new java.awt.Color(255, 0, 0));
        back_btn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\back.png")); // NOI18N
        back_btn.setText("BACK");
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back_btn)
                            .addComponent(jLabel2))
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void AdminDetails(){
        try{
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supermarketDB", "User_1", "1234");
            st = conn.createStatement();
            String Query = "SELECT * FROM User_1.ADMIN";
            rs = st.executeQuery(Query);
            //JOptionPane.showMessageDialog(this, "Admin Updated Successfully!");
            while(rs.next()){
                String id = rs.getString("ADMINID");
                adminID_lbl.setText(id);
                String name = rs.getString("ADMINNAME");
                adminName_lbl.setText(name);
                String username = rs.getString("ADMINUN");
                adminUN_lbl.setText(username);
                String pass = rs.getString("ADMINPASS");
                adminPass_lbl.setText(pass);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    private void logout_btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_btn1MouseClicked

    private void logout_btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btn2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_btn2MouseClicked

    private void adminUN_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUN_lblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminUN_lblMouseClicked

    private void adminPass_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPass_lblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminPass_lblMouseClicked

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_update_btnActionPerformed

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        //navigate to admin menu
        new AdminMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnMouseClicked

    private void logout_btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btn6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_btn6MouseClicked

    private void logout_btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btn7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_btn7MouseClicked

    private void adminName_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminName_lblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminName_lblMouseClicked

    private void adminID_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminID_lblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminID_lblMouseClicked

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        //close button
        System.exit(0);
    }//GEN-LAST:event_close_btnMouseClicked

    private void update_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_btnMouseClicked
        //navigate to admin update
        new UpdateAdmin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_update_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminID_lbl;
    private javax.swing.JLabel adminName_lbl;
    private javax.swing.JLabel adminPass_lbl;
    private javax.swing.JLabel adminUN_lbl;
    private javax.swing.JLabel back_btn;
    private javax.swing.JLabel close_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logout_btn1;
    private javax.swing.JLabel logout_btn2;
    private javax.swing.JLabel logout_btn6;
    private javax.swing.JLabel logout_btn7;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
