/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarketapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
        showDate();
        showTime();
    }
    
    //show Date
    public void showDate(){
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy");
        String date = f.format(d);
        date_lbl.setText(date);
    }
    
    //show time
    public void showTime(){
        new Timer(0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date t = new Date();
                SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss a");
                String time = f.format(t);
                time_lbl.setText(time);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close_btn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        bill_pnl = new javax.swing.JPanel();
        billHis_btn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sell_pnl = new javax.swing.JPanel();
        seller_btn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pro_pnl = new javax.swing.JPanel();
        pro_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cat_pnl = new javax.swing.JPanel();
        cat_btn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        admin_pnl = new javax.swing.JPanel();
        admin_btn = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        date_lbl = new javax.swing.JLabel();
        time_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        close_btn.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\close-box.png")); // NOI18N
        close_btn.setToolTipText("");
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\grocerypals_small.png")); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\cart_small.png")); // NOI18N

        jPanel8.setBackground(new java.awt.Color(87, 145, 179));

        bill_pnl.setBackground(new java.awt.Color(51, 51, 51));
        bill_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bill_pnlMouseClicked(evt);
            }
        });

        billHis_btn.setBackground(new java.awt.Color(255, 0, 0));
        billHis_btn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        billHis_btn.setForeground(new java.awt.Color(87, 145, 179));
        billHis_btn.setText("BILL HISTORY");
        billHis_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billHis_btnMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\bill.png")); // NOI18N

        javax.swing.GroupLayout bill_pnlLayout = new javax.swing.GroupLayout(bill_pnl);
        bill_pnl.setLayout(bill_pnlLayout);
        bill_pnlLayout.setHorizontalGroup(
            bill_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_pnlLayout.createSequentialGroup()
                .addGroup(bill_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bill_pnlLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(billHis_btn))
                    .addGroup(bill_pnlLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel5)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        bill_pnlLayout.setVerticalGroup(
            bill_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_pnlLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(billHis_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        sell_pnl.setBackground(new java.awt.Color(51, 51, 51));
        sell_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sell_pnlMouseClicked(evt);
            }
        });

        seller_btn.setBackground(new java.awt.Color(255, 0, 0));
        seller_btn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        seller_btn.setForeground(new java.awt.Color(87, 145, 179));
        seller_btn.setText("MANAGE SELLERS");
        seller_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seller_btnMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\seller.png")); // NOI18N

        javax.swing.GroupLayout sell_pnlLayout = new javax.swing.GroupLayout(sell_pnl);
        sell_pnl.setLayout(sell_pnlLayout);
        sell_pnlLayout.setHorizontalGroup(
            sell_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sell_pnlLayout.createSequentialGroup()
                .addGroup(sell_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sell_pnlLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3))
                    .addGroup(sell_pnlLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(seller_btn)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        sell_pnlLayout.setVerticalGroup(
            sell_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sell_pnlLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(seller_btn)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pro_pnl.setBackground(new java.awt.Color(51, 51, 51));
        pro_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pro_pnlMouseClicked(evt);
            }
        });

        pro_btn.setBackground(new java.awt.Color(255, 0, 0));
        pro_btn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        pro_btn.setForeground(new java.awt.Color(87, 145, 179));
        pro_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pro_btn.setText("MANAGE PRODUCTS");
        pro_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pro_btnMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\food.png")); // NOI18N

        javax.swing.GroupLayout pro_pnlLayout = new javax.swing.GroupLayout(pro_pnl);
        pro_pnl.setLayout(pro_pnlLayout);
        pro_pnlLayout.setHorizontalGroup(
            pro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pro_pnlLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(pro_btn)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pro_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
        );
        pro_pnlLayout.setVerticalGroup(
            pro_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pro_pnlLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pro_btn)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        cat_pnl.setBackground(new java.awt.Color(51, 51, 51));
        cat_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cat_pnlMouseClicked(evt);
            }
        });

        cat_btn.setBackground(new java.awt.Color(255, 0, 0));
        cat_btn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cat_btn.setForeground(new java.awt.Color(87, 145, 179));
        cat_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cat_btn.setText("<html>\nMANAGE PRODUCT<br>\n<center>CATEGORIES</center>\n</html>"); // NOI18N
        cat_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cat_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cat_btnMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\cat.png")); // NOI18N

        javax.swing.GroupLayout cat_pnlLayout = new javax.swing.GroupLayout(cat_pnl);
        cat_pnl.setLayout(cat_pnlLayout);
        cat_pnlLayout.setHorizontalGroup(
            cat_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cat_pnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cat_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(cat_pnlLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cat_pnlLayout.setVerticalGroup(
            cat_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cat_pnlLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cat_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        admin_pnl.setBackground(new java.awt.Color(51, 51, 51));
        admin_pnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_pnlMouseClicked(evt);
            }
        });

        admin_btn.setBackground(new java.awt.Color(255, 0, 0));
        admin_btn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        admin_btn.setForeground(new java.awt.Color(87, 145, 179));
        admin_btn.setText("ADMIN PROFILE");
        admin_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admin_btnMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\profile.png")); // NOI18N

        javax.swing.GroupLayout admin_pnlLayout = new javax.swing.GroupLayout(admin_pnl);
        admin_pnl.setLayout(admin_pnlLayout);
        admin_pnlLayout.setHorizontalGroup(
            admin_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_pnlLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(admin_btn)
                .addGap(56, 56, 56))
            .addGroup(admin_pnlLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        admin_pnlLayout.setVerticalGroup(
            admin_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_pnlLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(admin_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(bill_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(admin_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(pro_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(cat_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(sell_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cat_pnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pro_pnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sell_pnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bill_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1006, Short.MAX_VALUE)
                .addComponent(close_btn)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close_btn)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel7)))
                .addGap(59, 59, 59)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(87, 145, 179));

        date_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        date_lbl.setForeground(new java.awt.Color(51, 51, 51));
        date_lbl.setText("Date");

        time_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        time_lbl.setForeground(new java.awt.Color(51, 51, 51));
        time_lbl.setText("Time");

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DASHBOARD");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TIME :");

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DATE :");

        logout_btn.setBackground(new java.awt.Color(255, 0, 0));
        logout_btn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\power.png")); // NOI18N
        logout_btn.setText("LOGOUT");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logout_btn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(time_lbl))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date_lbl))
                            .addComponent(jLabel2))
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(date_lbl))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(time_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_btn)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pro_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pro_btnMouseClicked
        
    }//GEN-LAST:event_pro_btnMouseClicked

    private void seller_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seller_btnMouseClicked
        
    }//GEN-LAST:event_seller_btnMouseClicked

    private void cat_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cat_btnMouseClicked
        
    }//GEN-LAST:event_cat_btnMouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        //navigate to login
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_btnMouseClicked

    private void admin_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_btnMouseClicked
        
    }//GEN-LAST:event_admin_btnMouseClicked

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        //close button
        System.exit(0);
    }//GEN-LAST:event_close_btnMouseClicked

    private void billHis_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billHis_btnMouseClicked
        
    }//GEN-LAST:event_billHis_btnMouseClicked

    private void pro_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pro_pnlMouseClicked
        //navigate to products
        new Products().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pro_pnlMouseClicked

    private void cat_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cat_pnlMouseClicked
        //navigate to categories
        new Categories().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cat_pnlMouseClicked

    private void sell_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sell_pnlMouseClicked
        //navigate to seller
        new Seller().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sell_pnlMouseClicked

    private void bill_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_pnlMouseClicked
        //navigate to bill history
        new BillHistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bill_pnlMouseClicked

    private void admin_pnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admin_pnlMouseClicked
        //navigate to admin profile
        new AdminProfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_admin_pnlMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admin_btn;
    private javax.swing.JPanel admin_pnl;
    private javax.swing.JLabel billHis_btn;
    private javax.swing.JPanel bill_pnl;
    private javax.swing.JLabel cat_btn;
    private javax.swing.JPanel cat_pnl;
    private javax.swing.JLabel close_btn;
    public javax.swing.JLabel date_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JLabel pro_btn;
    private javax.swing.JPanel pro_pnl;
    private javax.swing.JPanel sell_pnl;
    private javax.swing.JLabel seller_btn;
    public javax.swing.JLabel time_lbl;
    // End of variables declaration//GEN-END:variables
}
