/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarketapp;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ASUS
 */
public class BillPoint extends javax.swing.JFrame {

    /**
     * Creates new form BillPoint
     */
    public BillPoint() {
        initComponents();
        SelectProduct();
        GetCategory();
        //SellerName();
        showDate();
        showTime();
    }
    
    //database connection
    Connection conn = null;
    Statement st = null;
    ResultSet rs = null;
    
    //product read
    public void SelectProduct(){
        try{
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supermarketDB", "User_1", "1234");
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM User_1.PRODUCTS");
            proList_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    //to update remaining products
    int proID, newQty;
    
    public void remUpdate(){
        
        newQty = remQty - Integer.valueOf(proQty_txt.getText());
        
        try{
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supermarketDB", "User_1", "1234");
            String Query = "UPDATE User_1.PRODUCTS SET PROQTY="+newQty+""+"WHERE PROID="+proID;
            Statement EDIT = conn.createStatement();
            EDIT.executeUpdate(Query);
            //JOptionPane.showMessageDialog(this, "Product Updated Successfully!");
            SelectProduct();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    //read categories
    private void GetCategory(){
        try{
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supermarketDB", "User_1", "1234");
            st = conn.createStatement();
            String Query = "SELECT * FROM User_1.CATEGORIES";
            rs = st.executeQuery(Query);
            while(rs.next()){
                String cat = rs.getString("CATNAME");
                proCat_Cbox.addItem(cat);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    //read seller name
    /*public void SellerName(){
         
        try{
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supermarketDB", "User_1", "1234");
            st = conn.createStatement();
            String Query = "SELECT * FROM User_1.SELLER WHERE SELLERNAME="+sellerName;
            rs = st.executeQuery(Query);
            while(rs.next()){
                String name = rs.getString("SELLERNAME");
                sellName_lbl.setText(name);
                //proCat_Cbox.addItem(cat);
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }*/
    
    //show Date
    public void showDate(){
        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy");
        String date = f.format(d);
        billDate_lbl.setText(date);
    }
    
    //show time
    public void showTime(){
        new Timer(0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date t = new Date();
                SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss a");
                String time = f.format(t);
                billTime_lbl.setText(time);
            }
        }).start();
    }
    
    //clear all fields
    public void clearAll(){
        proName_txt.setText("");
        proQty_txt.setText("");
        billID_txt.setText("");
        cusName_txt.setText("");
        bill_txt.setText("");
        finalTot_lbl.setText("");
        finalQty_lbl.setText("");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logout_btn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sellName_lbl = new javax.swing.JLabel();
        billDate_lbl = new javax.swing.JLabel();
        billTime_lbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        billID_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cusName_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill_txt = new javax.swing.JTextArea();
        print_btn = new javax.swing.JButton();
        finalTot_lbl = new javax.swing.JLabel();
        finalQty_lbl = new javax.swing.JLabel();
        ok_btn = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel8 = new javax.swing.JLabel();
        proCat_Cbox = new javax.swing.JComboBox<>();
        filter_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        proList_tbl = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        proQty_txt = new javax.swing.JTextField();
        proName_txt = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        clear_btn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        close_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(87, 145, 179));

        logout_btn.setBackground(new java.awt.Color(255, 0, 0));
        logout_btn.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\power.png")); // NOI18N
        logout_btn.setText("LOGOUT");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SELLER :");

        sellName_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        sellName_lbl.setForeground(new java.awt.Color(51, 51, 51));
        sellName_lbl.setText("Name");

        billDate_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        billDate_lbl.setForeground(new java.awt.Color(51, 51, 51));
        billDate_lbl.setText("Date");

        billTime_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        billTime_lbl.setForeground(new java.awt.Color(51, 51, 51));
        billTime_lbl.setText("Time");

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BILLING POINT");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TIME :");

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DATE :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(billTime_lbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(billDate_lbl))
                            .addComponent(logout_btn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sellName_lbl))
                            .addComponent(jLabel2))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sellName_lbl))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(billDate_lbl))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(billTime_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_btn)
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        billID_txt.setBackground(new java.awt.Color(51, 51, 51));
        billID_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        billID_txt.setForeground(new java.awt.Color(255, 255, 255));
        billID_txt.setBorder(null);
        billID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billID_txtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 145, 179));
        jLabel3.setText("BILL ID         :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(87, 145, 179));
        jLabel7.setText("CUSTOMER :");

        cusName_txt.setBackground(new java.awt.Color(51, 51, 51));
        cusName_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cusName_txt.setForeground(new java.awt.Color(255, 255, 255));
        cusName_txt.setBorder(null);

        bill_txt.setEditable(false);
        bill_txt.setBackground(new java.awt.Color(169, 175, 179));
        bill_txt.setColumns(20);
        bill_txt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        bill_txt.setRows(5);
        jScrollPane2.setViewportView(bill_txt);

        print_btn.setBackground(new java.awt.Color(87, 145, 179));
        print_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        print_btn.setText("PRINT");
        print_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                print_btnMouseClicked(evt);
            }
        });
        print_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_btnActionPerformed(evt);
            }
        });

        finalTot_lbl.setBackground(new java.awt.Color(87, 145, 179));
        finalTot_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        finalTot_lbl.setForeground(new java.awt.Color(87, 145, 179));
        finalTot_lbl.setText("TOTAL");

        finalQty_lbl.setBackground(new java.awt.Color(87, 145, 179));
        finalQty_lbl.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        finalQty_lbl.setForeground(new java.awt.Color(87, 145, 179));
        finalQty_lbl.setText("QTY");

        ok_btn.setBackground(new java.awt.Color(204, 204, 204));
        ok_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ok_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\checkbox.png")); // NOI18N
        ok_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_btnMouseClicked(evt);
            }
        });
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(87, 145, 179));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("PRODUCTS LIST");

        proCat_Cbox.setBackground(new java.awt.Color(51, 51, 51));
        proCat_Cbox.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        proCat_Cbox.setForeground(new java.awt.Color(87, 145, 179));
        proCat_Cbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beverage", "Vegetable", "Meat" }));
        proCat_Cbox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        proCat_Cbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                proCat_CboxItemStateChanged(evt);
            }
        });
        proCat_Cbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proCat_CboxMouseClicked(evt);
            }
        });
        proCat_Cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proCat_CboxActionPerformed(evt);
            }
        });

        filter_btn.setBackground(new java.awt.Color(51, 51, 51));
        filter_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        filter_btn.setForeground(new java.awt.Color(87, 145, 179));
        filter_btn.setText("FILTER");
        filter_btn.setBorder(null);
        filter_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filter_btnMouseClicked(evt);
            }
        });
        filter_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_btnActionPerformed(evt);
            }
        });

        refresh_btn.setBackground(new java.awt.Color(51, 51, 51));
        refresh_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        refresh_btn.setForeground(new java.awt.Color(87, 145, 179));
        refresh_btn.setText("REFRESH");
        refresh_btn.setBorder(null);
        refresh_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_btnMouseClicked(evt);
            }
        });
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        proList_tbl.setBackground(new java.awt.Color(154, 161, 166));
        proList_tbl.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        proList_tbl.setForeground(new java.awt.Color(51, 51, 51));
        proList_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "QUANTITY", "PRICE", "CATEGORY"
            }
        ));
        proList_tbl.setIntercellSpacing(new java.awt.Dimension(0, 0));
        proList_tbl.setRowHeight(25);
        proList_tbl.setSelectionBackground(new java.awt.Color(87, 145, 179));
        proList_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proList_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(proList_tbl);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("ITEM          :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("QUANTITY :");

        proQty_txt.setBackground(new java.awt.Color(87, 145, 179));
        proQty_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        proQty_txt.setForeground(new java.awt.Color(255, 255, 255));
        proQty_txt.setBorder(null);
        proQty_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proQty_txtActionPerformed(evt);
            }
        });

        proName_txt.setEditable(false);
        proName_txt.setBackground(new java.awt.Color(87, 145, 179));
        proName_txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        proName_txt.setForeground(new java.awt.Color(255, 255, 255));
        proName_txt.setBorder(null);
        proName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proName_txtActionPerformed(evt);
            }
        });

        add_btn.setBackground(new java.awt.Color(51, 51, 51));
        add_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        add_btn.setForeground(new java.awt.Color(87, 145, 179));
        add_btn.setText("ADD TO BILL");
        add_btn.setBorder(null);
        add_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_btnMouseClicked(evt);
            }
        });
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        clear_btn.setBackground(new java.awt.Color(51, 51, 51));
        clear_btn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        clear_btn.setForeground(new java.awt.Color(87, 145, 179));
        clear_btn.setText("CLEAR");
        clear_btn.setBorder(null);
        clear_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear_btnMouseClicked(evt);
            }
        });
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));

        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(proCat_Cbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(filter_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(refresh_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(proQty_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(proName_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(add_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(clear_btn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                    .addComponent(proCat_Cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(filter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(refresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(10, 10, 10)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator2)
                                        .addComponent(proQty_txt)
                                        .addComponent(proName_txt, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proCat_Cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filter_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(proName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(proQty_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        close_btn.setBackground(new java.awt.Color(255, 255, 255));
        close_btn.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\close-box.png")); // NOI18N
        close_btn.setToolTipText("");
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\grocerypals_small.png")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity :");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(87, 145, 179));
        jLabel10.setText("Rs.");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total :");

        jSeparator4.setBackground(new java.awt.Color(87, 145, 179));
        jSeparator4.setForeground(new java.awt.Color(87, 145, 179));

        jSeparator5.setBackground(new java.awt.Color(87, 145, 179));
        jSeparator5.setForeground(new java.awt.Color(87, 145, 179));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Desktop\\OOP Project\\Icons\\cart_small.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(jSeparator4)
                                    .addComponent(billID_txt)
                                    .addComponent(cusName_txt))
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalQty_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalTot_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(print_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finalQty_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(finalTot_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(billID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cusName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void billID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billID_txtActionPerformed

    private void proCat_CboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proCat_CboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proCat_CboxActionPerformed

    private void proName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proName_txtActionPerformed

    private void filter_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filter_btnActionPerformed

    int i = 0, finalQty = 0;
    double proTot = 0.0, finalTot = 0.0;
    
    private void add_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_btnMouseClicked
        //product add
        if(proName_txt.getText().isEmpty()||proQty_txt.getText().isEmpty()||proQty_txt.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "Quantity cannot be NULL!", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(remQty <= Integer.valueOf(proQty_txt.getText())){
            JOptionPane.showMessageDialog(this, "Not enough in stock!");
        }else{
            i++;
            proTot = unitPrice * Double.valueOf(proQty_txt.getText());
            finalTot = finalTot + proTot;
            finalQty = finalQty + Integer.valueOf(proQty_txt.getText());
            if(i == 1){
                bill_txt.setText(bill_txt.getText()+"=====GROCERYPALS - Your Daily Pal=====\n" +"Customer: "+cusName_txt.getText()+"     Seller: "+sellName_lbl.getText()+"\n" +"Bill Date: "+billDate_lbl.getText()+"     Bill Time: "+billTime_lbl.getText()+"\n" + "NUM     PRODUCT     U.PRICE     QUANTITY     TOTAL\n" + i +"            "+proName_txt.getText()+"                    "+unitPrice+"            "+proQty_txt.getText()+"                      "+proTot+"\n");
            }else{
                bill_txt.setText(bill_txt.getText()+i +"            "+proName_txt.getText()+"                    "+unitPrice+"            "+proQty_txt.getText()+"                      "+proTot+"\n");
            }
            finalTot_lbl.setText(String.valueOf(finalTot));
            finalQty_lbl.setText(String.valueOf(finalQty));
            remUpdate();
        }
    }//GEN-LAST:event_add_btnMouseClicked

    private void print_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_print_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh_btnActionPerformed

    double unitPrice;
    int remQty;
    private void proList_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proList_tblMouseClicked
        //product list select
        DefaultTableModel model = (DefaultTableModel)proList_tbl.getModel();
        int Index = proList_tbl.getSelectedRow();
        //catID_txt.setText(model.getValueAt(Index, 0).toString());
        proID = Integer.valueOf(model.getValueAt(Index, 0).toString());
        proName_txt.setText(model.getValueAt(Index, 1).toString());
        remQty = Integer.valueOf(model.getValueAt(Index, 2).toString());
        unitPrice = Double.valueOf(model.getValueAt(Index, 3).toString());
        //catDesc_txt.setText(model.getValueAt(Index, 2).toString());
        //System.out.println(newQty);
    }//GEN-LAST:event_proList_tblMouseClicked

    private void print_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_print_btnMouseClicked
        //print bill
        try{
            if(billID_txt.getText().isEmpty()||cusName_txt.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Bill ID/Customer Name cannot be EMPTY!", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(bill_txt.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "ADD a product first!", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                try{
                    conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supermarketDB", "User_1", "1234");
                    PreparedStatement ADD = conn.prepareStatement("INSERT INTO BILL VALUES (?,?,?,?,?,?,?)");
                    ADD.setInt(1, Integer.valueOf(billID_txt.getText()));
                    ADD.setString(2, cusName_txt.getText());
                    ADD.setString(3, sellName_lbl.getText());
                    ADD.setString(4, billDate_lbl.getText());
                    ADD.setString(5, billTime_lbl.getText());
                    ADD.setInt(6, Integer.valueOf(finalQty_lbl.getText()));
                    ADD.setDouble(7, Double.valueOf(finalTot_lbl.getText()));
                    int row = ADD.executeUpdate();
                    //System.out.println("Wade goda");
                    conn.close();
                }catch(Exception ex){
                    ex.printStackTrace();
                }
                bill_txt.print();
                JOptionPane.showMessageDialog(this, "Bill Printed successfully!");
                clearAll();
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_print_btnMouseClicked

    private void clear_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear_btnMouseClicked
        //fields clear
        //billID_txt.setText("");
        proName_txt.setText("");
        proQty_txt.setText("");
        //proPrice_txt.setText("");
    }//GEN-LAST:event_clear_btnMouseClicked

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        //navigate to login
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_btnMouseClicked

    private void proCat_CboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proCat_CboxMouseClicked
        
    }//GEN-LAST:event_proCat_CboxMouseClicked

    private void filter_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filter_btnMouseClicked
        //filter products
        try{
            conn = DriverManager.getConnection("jdbc:derby://localhost:1527/supermarketDB", "User_1", "1234");
            st = conn.createStatement();
            rs = st.executeQuery("SELECT * FROM User_1.PRODUCTS WHERE PROCAT='"+proCat_Cbox.getSelectedItem().toString()+"'");
            proList_tbl.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_filter_btnMouseClicked

    private void proCat_CboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_proCat_CboxItemStateChanged
        
    }//GEN-LAST:event_proCat_CboxItemStateChanged

    private void refresh_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseClicked
        //refresh table
        SelectProduct();
    }//GEN-LAST:event_refresh_btnMouseClicked

    private void ok_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_btnMouseClicked
        //bill footer print
        if(proName_txt.getText().isEmpty()||proQty_txt.getText().isEmpty()||proQty_txt.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "ADD a product first!", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            bill_txt.setText(bill_txt.getText()+"Thank you for shopping with us!\n"+"Total QTY: "+finalQty+"     Total:"+finalTot);
        }
    }//GEN-LAST:event_ok_btnMouseClicked

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        //application exit
        System.exit(0);
    }//GEN-LAST:event_close_btnMouseClicked

    private void proQty_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proQty_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proQty_txtActionPerformed

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clear_btnActionPerformed

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ok_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPoint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    public javax.swing.JLabel billDate_lbl;
    private javax.swing.JTextField billID_txt;
    public javax.swing.JLabel billTime_lbl;
    private javax.swing.JTextArea bill_txt;
    private javax.swing.JButton clear_btn;
    private javax.swing.JLabel close_btn;
    private javax.swing.JTextField cusName_txt;
    private javax.swing.JButton filter_btn;
    private javax.swing.JLabel finalQty_lbl;
    private javax.swing.JLabel finalTot_lbl;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel logout_btn;
    private javax.swing.JButton ok_btn;
    private javax.swing.JButton print_btn;
    private javax.swing.JComboBox<String> proCat_Cbox;
    private javax.swing.JTable proList_tbl;
    private javax.swing.JTextField proName_txt;
    private javax.swing.JTextField proQty_txt;
    private javax.swing.JButton refresh_btn;
    public javax.swing.JLabel sellName_lbl;
    // End of variables declaration//GEN-END:variables
}
